### PR TITLE
Change deprecated functions, update CI and deps, follow Deno code style and fix lints

### PR DESCRIPTION
**Pull request by UltiRequiem**
- Change deprecated function:
`Deno.writeAllSync` -> https://deno.land/std@0.119.0/streams/conversion.ts#L378

- Update CI to ensure follow the Deno code style, in every commit:

```sh
$ deno lint
$ deno test
$ deno fmt --check
```

- I also add a schedule action to update Deps:
https://github.com/hayd/deno-udd#scheduled-github-action

- All dependencies bumped to their latest version and working correctly
-  Lints fixed
- Format problems fixed

### CODE REVIEW

**Comment by UltiRequiem** [comment]
If you want to use the code from this pull request until it gets merged you can 👇🏽 

```typescript
import Kia from "https://raw.githubusercontent.com/UltiRequiem/kia/master/mod.ts"
```

**Comment by HarryPeach** [comment]
Hey, thanks for taking the time to do a PR! Most of this looks good to me, but there are a couple of things to note:

- Deno fmt by default switches everything to spaces while this repo uses tabs, and this is reflected in all the files committed. By the looks of it there is a '--options-use-tabs' flag for fmt, so if you could add this, reformat, and then resubmit that'd be grand.

- It would be nice if the dependency checker perhaps checked weekly rather than daily

If you make these changes, there's only a few style/convention things that I'll change and then we can merge. Cheers!

EDIT: It also seems you removed the CI run for pull requests which is useful to have

**Comment by UltiRequiem** [comment]
[This action](https://github.com/HarryPeach/kia/pull/10/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3) will run on PR and Pushes as CI.

The workflow to update deps now runs weekly as you asked 😆 

You can configure the format with the `deno.json` config file, docs 👇🏽 

https://deno.land/manual@v1.16.0/getting_started/configuration_file

**Review by HarryPeach — APPROVED** [review]
All LGTM, thanks for the contribution! :shipit:

**Pull request merged**
